### ISSUE TITLE
Todo list 정리

### ISSUE THREAD

**Issue by arsgsg1** [arsgsg1/Mediate#1]
### 기능 개발 정리
- [ ] 받은 알림 확인 - 내가 보낸 신청 및 응답
- [x] 숙제, 진행도 저장
### 기능 외 개발 정리
- [ ] 에러 메시지 포맷 통일
- [ ] DB DDL 이력 관리
- [ ] 테스트 코드 작성
- [ ] 로그인 로그아웃 고도화

tutee의 major 저장해야함
리스트 조회 시 페이징
한 튜터, 튜티가 요청을 중복해서 여러 번 보낼 경우 한 번만 저장하도록 처리
실행 시 DB에 값을 미리 저장하는 데이터 제너레이터 만들기

성능 병목 포인트
1. 조회 수
2. 숙제, 진행도 C,R,D
3. 댓글

강결합 포인트
1. 받은 알림 (튜터링 수락, 거절, 제안 이벤트)
